name: Pack Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install ZIP
        uses: montudor/action-zip@v1
        
      - name: Setup NPM packages
        run: npm install
        
      - name: Build and Pack extension
        run: npm run build-zip; mv chrome-extension.zip dist/extension.zip

      - name: Create or Update Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/extension.zip
          tag_name: ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false